/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as DashboarduserImport } from './routes/dashboard_user'
import { Route as DashboardtrainerImport } from './routes/dashboard_trainer'
import { Route as DashboardadminImport } from './routes/dashboard_admin'
import { Route as IndexImport } from './routes/index'
import { Route as DashboarduserIndexImport } from './routes/dashboard_user/index'
import { Route as DashboardtrainerIndexImport } from './routes/dashboard_trainer/index'
import { Route as DashboardadminIndexImport } from './routes/dashboard_admin/index'
import { Route as DashboarduserTuitionImport } from './routes/dashboard_user/tuition'
import { Route as DashboarduserTournamentImport } from './routes/dashboard_user/tournament'
import { Route as DashboarduserRequestsImport } from './routes/dashboard_user/requests'
import { Route as DashboarduserCategoriesImport } from './routes/dashboard_user/categories'
import { Route as DashboardtrainerTournamentmanagementImport } from './routes/dashboard_trainer/tournament_management'
import { Route as DashboardadminRolemanagementImport } from './routes/dashboard_admin/role_management'
import { Route as DashboardadminRequestsImport } from './routes/dashboard_admin/requests'
import { Route as DashboardadminCategorymanagementImport } from './routes/dashboard_admin/category_management'
import { Route as AuthSigninImport } from './routes/auth/signin'
import { Route as AuthLoginImport } from './routes/auth/login'

// Create/Update Routes

const DashboarduserRoute = DashboarduserImport.update({
  id: '/dashboard_user',
  path: '/dashboard_user',
  getParentRoute: () => rootRoute,
} as any)

const DashboardtrainerRoute = DashboardtrainerImport.update({
  id: '/dashboard_trainer',
  path: '/dashboard_trainer',
  getParentRoute: () => rootRoute,
} as any)

const DashboardadminRoute = DashboardadminImport.update({
  id: '/dashboard_admin',
  path: '/dashboard_admin',
  getParentRoute: () => rootRoute,
} as any)

const IndexRoute = IndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

const DashboarduserIndexRoute = DashboarduserIndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DashboarduserRoute,
} as any)

const DashboardtrainerIndexRoute = DashboardtrainerIndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DashboardtrainerRoute,
} as any)

const DashboardadminIndexRoute = DashboardadminIndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DashboardadminRoute,
} as any)

const DashboarduserTuitionRoute = DashboarduserTuitionImport.update({
  id: '/tuition',
  path: '/tuition',
  getParentRoute: () => DashboarduserRoute,
} as any)

const DashboarduserTournamentRoute = DashboarduserTournamentImport.update({
  id: '/tournament',
  path: '/tournament',
  getParentRoute: () => DashboarduserRoute,
} as any)

const DashboarduserRequestsRoute = DashboarduserRequestsImport.update({
  id: '/requests',
  path: '/requests',
  getParentRoute: () => DashboarduserRoute,
} as any)

const DashboarduserCategoriesRoute = DashboarduserCategoriesImport.update({
  id: '/categories',
  path: '/categories',
  getParentRoute: () => DashboarduserRoute,
} as any)

const DashboardtrainerTournamentmanagementRoute =
  DashboardtrainerTournamentmanagementImport.update({
    id: '/tournament_management',
    path: '/tournament_management',
    getParentRoute: () => DashboardtrainerRoute,
  } as any)

const DashboardadminRolemanagementRoute =
  DashboardadminRolemanagementImport.update({
    id: '/role_management',
    path: '/role_management',
    getParentRoute: () => DashboardadminRoute,
  } as any)

const DashboardadminRequestsRoute = DashboardadminRequestsImport.update({
  id: '/requests',
  path: '/requests',
  getParentRoute: () => DashboardadminRoute,
} as any)

const DashboardadminCategorymanagementRoute =
  DashboardadminCategorymanagementImport.update({
    id: '/category_management',
    path: '/category_management',
    getParentRoute: () => DashboardadminRoute,
  } as any)

const AuthSigninRoute = AuthSigninImport.update({
  id: '/auth/signin',
  path: '/auth/signin',
  getParentRoute: () => rootRoute,
} as any)

const AuthLoginRoute = AuthLoginImport.update({
  id: '/auth/login',
  path: '/auth/login',
  getParentRoute: () => rootRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/dashboard_admin': {
      id: '/dashboard_admin'
      path: '/dashboard_admin'
      fullPath: '/dashboard_admin'
      preLoaderRoute: typeof DashboardadminImport
      parentRoute: typeof rootRoute
    }
    '/dashboard_trainer': {
      id: '/dashboard_trainer'
      path: '/dashboard_trainer'
      fullPath: '/dashboard_trainer'
      preLoaderRoute: typeof DashboardtrainerImport
      parentRoute: typeof rootRoute
    }
    '/dashboard_user': {
      id: '/dashboard_user'
      path: '/dashboard_user'
      fullPath: '/dashboard_user'
      preLoaderRoute: typeof DashboarduserImport
      parentRoute: typeof rootRoute
    }
    '/auth/login': {
      id: '/auth/login'
      path: '/auth/login'
      fullPath: '/auth/login'
      preLoaderRoute: typeof AuthLoginImport
      parentRoute: typeof rootRoute
    }
    '/auth/signin': {
      id: '/auth/signin'
      path: '/auth/signin'
      fullPath: '/auth/signin'
      preLoaderRoute: typeof AuthSigninImport
      parentRoute: typeof rootRoute
    }
    '/dashboard_admin/category_management': {
      id: '/dashboard_admin/category_management'
      path: '/category_management'
      fullPath: '/dashboard_admin/category_management'
      preLoaderRoute: typeof DashboardadminCategorymanagementImport
      parentRoute: typeof DashboardadminImport
    }
    '/dashboard_admin/requests': {
      id: '/dashboard_admin/requests'
      path: '/requests'
      fullPath: '/dashboard_admin/requests'
      preLoaderRoute: typeof DashboardadminRequestsImport
      parentRoute: typeof DashboardadminImport
    }
    '/dashboard_admin/role_management': {
      id: '/dashboard_admin/role_management'
      path: '/role_management'
      fullPath: '/dashboard_admin/role_management'
      preLoaderRoute: typeof DashboardadminRolemanagementImport
      parentRoute: typeof DashboardadminImport
    }
    '/dashboard_trainer/tournament_management': {
      id: '/dashboard_trainer/tournament_management'
      path: '/tournament_management'
      fullPath: '/dashboard_trainer/tournament_management'
      preLoaderRoute: typeof DashboardtrainerTournamentmanagementImport
      parentRoute: typeof DashboardtrainerImport
    }
    '/dashboard_user/categories': {
      id: '/dashboard_user/categories'
      path: '/categories'
      fullPath: '/dashboard_user/categories'
      preLoaderRoute: typeof DashboarduserCategoriesImport
      parentRoute: typeof DashboarduserImport
    }
    '/dashboard_user/requests': {
      id: '/dashboard_user/requests'
      path: '/requests'
      fullPath: '/dashboard_user/requests'
      preLoaderRoute: typeof DashboarduserRequestsImport
      parentRoute: typeof DashboarduserImport
    }
    '/dashboard_user/tournament': {
      id: '/dashboard_user/tournament'
      path: '/tournament'
      fullPath: '/dashboard_user/tournament'
      preLoaderRoute: typeof DashboarduserTournamentImport
      parentRoute: typeof DashboarduserImport
    }
    '/dashboard_user/tuition': {
      id: '/dashboard_user/tuition'
      path: '/tuition'
      fullPath: '/dashboard_user/tuition'
      preLoaderRoute: typeof DashboarduserTuitionImport
      parentRoute: typeof DashboarduserImport
    }
    '/dashboard_admin/': {
      id: '/dashboard_admin/'
      path: '/'
      fullPath: '/dashboard_admin/'
      preLoaderRoute: typeof DashboardadminIndexImport
      parentRoute: typeof DashboardadminImport
    }
    '/dashboard_trainer/': {
      id: '/dashboard_trainer/'
      path: '/'
      fullPath: '/dashboard_trainer/'
      preLoaderRoute: typeof DashboardtrainerIndexImport
      parentRoute: typeof DashboardtrainerImport
    }
    '/dashboard_user/': {
      id: '/dashboard_user/'
      path: '/'
      fullPath: '/dashboard_user/'
      preLoaderRoute: typeof DashboarduserIndexImport
      parentRoute: typeof DashboarduserImport
    }
  }
}

// Create and export the route tree

interface DashboardadminRouteChildren {
  DashboardadminCategorymanagementRoute: typeof DashboardadminCategorymanagementRoute
  DashboardadminRequestsRoute: typeof DashboardadminRequestsRoute
  DashboardadminRolemanagementRoute: typeof DashboardadminRolemanagementRoute
  DashboardadminIndexRoute: typeof DashboardadminIndexRoute
}

const DashboardadminRouteChildren: DashboardadminRouteChildren = {
  DashboardadminCategorymanagementRoute: DashboardadminCategorymanagementRoute,
  DashboardadminRequestsRoute: DashboardadminRequestsRoute,
  DashboardadminRolemanagementRoute: DashboardadminRolemanagementRoute,
  DashboardadminIndexRoute: DashboardadminIndexRoute,
}

const DashboardadminRouteWithChildren = DashboardadminRoute._addFileChildren(
  DashboardadminRouteChildren,
)

interface DashboardtrainerRouteChildren {
  DashboardtrainerTournamentmanagementRoute: typeof DashboardtrainerTournamentmanagementRoute
  DashboardtrainerIndexRoute: typeof DashboardtrainerIndexRoute
}

const DashboardtrainerRouteChildren: DashboardtrainerRouteChildren = {
  DashboardtrainerTournamentmanagementRoute:
    DashboardtrainerTournamentmanagementRoute,
  DashboardtrainerIndexRoute: DashboardtrainerIndexRoute,
}

const DashboardtrainerRouteWithChildren =
  DashboardtrainerRoute._addFileChildren(DashboardtrainerRouteChildren)

interface DashboarduserRouteChildren {
  DashboarduserCategoriesRoute: typeof DashboarduserCategoriesRoute
  DashboarduserRequestsRoute: typeof DashboarduserRequestsRoute
  DashboarduserTournamentRoute: typeof DashboarduserTournamentRoute
  DashboarduserTuitionRoute: typeof DashboarduserTuitionRoute
  DashboarduserIndexRoute: typeof DashboarduserIndexRoute
}

const DashboarduserRouteChildren: DashboarduserRouteChildren = {
  DashboarduserCategoriesRoute: DashboarduserCategoriesRoute,
  DashboarduserRequestsRoute: DashboarduserRequestsRoute,
  DashboarduserTournamentRoute: DashboarduserTournamentRoute,
  DashboarduserTuitionRoute: DashboarduserTuitionRoute,
  DashboarduserIndexRoute: DashboarduserIndexRoute,
}

const DashboarduserRouteWithChildren = DashboarduserRoute._addFileChildren(
  DashboarduserRouteChildren,
)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/dashboard_admin': typeof DashboardadminRouteWithChildren
  '/dashboard_trainer': typeof DashboardtrainerRouteWithChildren
  '/dashboard_user': typeof DashboarduserRouteWithChildren
  '/auth/login': typeof AuthLoginRoute
  '/auth/signin': typeof AuthSigninRoute
  '/dashboard_admin/category_management': typeof DashboardadminCategorymanagementRoute
  '/dashboard_admin/requests': typeof DashboardadminRequestsRoute
  '/dashboard_admin/role_management': typeof DashboardadminRolemanagementRoute
  '/dashboard_trainer/tournament_management': typeof DashboardtrainerTournamentmanagementRoute
  '/dashboard_user/categories': typeof DashboarduserCategoriesRoute
  '/dashboard_user/requests': typeof DashboarduserRequestsRoute
  '/dashboard_user/tournament': typeof DashboarduserTournamentRoute
  '/dashboard_user/tuition': typeof DashboarduserTuitionRoute
  '/dashboard_admin/': typeof DashboardadminIndexRoute
  '/dashboard_trainer/': typeof DashboardtrainerIndexRoute
  '/dashboard_user/': typeof DashboarduserIndexRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth/login': typeof AuthLoginRoute
  '/auth/signin': typeof AuthSigninRoute
  '/dashboard_admin/category_management': typeof DashboardadminCategorymanagementRoute
  '/dashboard_admin/requests': typeof DashboardadminRequestsRoute
  '/dashboard_admin/role_management': typeof DashboardadminRolemanagementRoute
  '/dashboard_trainer/tournament_management': typeof DashboardtrainerTournamentmanagementRoute
  '/dashboard_user/categories': typeof DashboarduserCategoriesRoute
  '/dashboard_user/requests': typeof DashboarduserRequestsRoute
  '/dashboard_user/tournament': typeof DashboarduserTournamentRoute
  '/dashboard_user/tuition': typeof DashboarduserTuitionRoute
  '/dashboard_admin': typeof DashboardadminIndexRoute
  '/dashboard_trainer': typeof DashboardtrainerIndexRoute
  '/dashboard_user': typeof DashboarduserIndexRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexRoute
  '/dashboard_admin': typeof DashboardadminRouteWithChildren
  '/dashboard_trainer': typeof DashboardtrainerRouteWithChildren
  '/dashboard_user': typeof DashboarduserRouteWithChildren
  '/auth/login': typeof AuthLoginRoute
  '/auth/signin': typeof AuthSigninRoute
  '/dashboard_admin/category_management': typeof DashboardadminCategorymanagementRoute
  '/dashboard_admin/requests': typeof DashboardadminRequestsRoute
  '/dashboard_admin/role_management': typeof DashboardadminRolemanagementRoute
  '/dashboard_trainer/tournament_management': typeof DashboardtrainerTournamentmanagementRoute
  '/dashboard_user/categories': typeof DashboarduserCategoriesRoute
  '/dashboard_user/requests': typeof DashboarduserRequestsRoute
  '/dashboard_user/tournament': typeof DashboarduserTournamentRoute
  '/dashboard_user/tuition': typeof DashboarduserTuitionRoute
  '/dashboard_admin/': typeof DashboardadminIndexRoute
  '/dashboard_trainer/': typeof DashboardtrainerIndexRoute
  '/dashboard_user/': typeof DashboarduserIndexRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/dashboard_admin'
    | '/dashboard_trainer'
    | '/dashboard_user'
    | '/auth/login'
    | '/auth/signin'
    | '/dashboard_admin/category_management'
    | '/dashboard_admin/requests'
    | '/dashboard_admin/role_management'
    | '/dashboard_trainer/tournament_management'
    | '/dashboard_user/categories'
    | '/dashboard_user/requests'
    | '/dashboard_user/tournament'
    | '/dashboard_user/tuition'
    | '/dashboard_admin/'
    | '/dashboard_trainer/'
    | '/dashboard_user/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth/login'
    | '/auth/signin'
    | '/dashboard_admin/category_management'
    | '/dashboard_admin/requests'
    | '/dashboard_admin/role_management'
    | '/dashboard_trainer/tournament_management'
    | '/dashboard_user/categories'
    | '/dashboard_user/requests'
    | '/dashboard_user/tournament'
    | '/dashboard_user/tuition'
    | '/dashboard_admin'
    | '/dashboard_trainer'
    | '/dashboard_user'
  id:
    | '__root__'
    | '/'
    | '/dashboard_admin'
    | '/dashboard_trainer'
    | '/dashboard_user'
    | '/auth/login'
    | '/auth/signin'
    | '/dashboard_admin/category_management'
    | '/dashboard_admin/requests'
    | '/dashboard_admin/role_management'
    | '/dashboard_trainer/tournament_management'
    | '/dashboard_user/categories'
    | '/dashboard_user/requests'
    | '/dashboard_user/tournament'
    | '/dashboard_user/tuition'
    | '/dashboard_admin/'
    | '/dashboard_trainer/'
    | '/dashboard_user/'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DashboardadminRoute: typeof DashboardadminRouteWithChildren
  DashboardtrainerRoute: typeof DashboardtrainerRouteWithChildren
  DashboarduserRoute: typeof DashboarduserRouteWithChildren
  AuthLoginRoute: typeof AuthLoginRoute
  AuthSigninRoute: typeof AuthSigninRoute
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DashboardadminRoute: DashboardadminRouteWithChildren,
  DashboardtrainerRoute: DashboardtrainerRouteWithChildren,
  DashboarduserRoute: DashboarduserRouteWithChildren,
  AuthLoginRoute: AuthLoginRoute,
  AuthSigninRoute: AuthSigninRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/dashboard_admin",
        "/dashboard_trainer",
        "/dashboard_user",
        "/auth/login",
        "/auth/signin"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/dashboard_admin": {
      "filePath": "dashboard_admin.tsx",
      "children": [
        "/dashboard_admin/category_management",
        "/dashboard_admin/requests",
        "/dashboard_admin/role_management",
        "/dashboard_admin/"
      ]
    },
    "/dashboard_trainer": {
      "filePath": "dashboard_trainer.tsx",
      "children": [
        "/dashboard_trainer/tournament_management",
        "/dashboard_trainer/"
      ]
    },
    "/dashboard_user": {
      "filePath": "dashboard_user.tsx",
      "children": [
        "/dashboard_user/categories",
        "/dashboard_user/requests",
        "/dashboard_user/tournament",
        "/dashboard_user/tuition",
        "/dashboard_user/"
      ]
    },
    "/auth/login": {
      "filePath": "auth/login.tsx"
    },
    "/auth/signin": {
      "filePath": "auth/signin.tsx"
    },
    "/dashboard_admin/category_management": {
      "filePath": "dashboard_admin/category_management.tsx",
      "parent": "/dashboard_admin"
    },
    "/dashboard_admin/requests": {
      "filePath": "dashboard_admin/requests.tsx",
      "parent": "/dashboard_admin"
    },
    "/dashboard_admin/role_management": {
      "filePath": "dashboard_admin/role_management.tsx",
      "parent": "/dashboard_admin"
    },
    "/dashboard_trainer/tournament_management": {
      "filePath": "dashboard_trainer/tournament_management.tsx",
      "parent": "/dashboard_trainer"
    },
    "/dashboard_user/categories": {
      "filePath": "dashboard_user/categories.tsx",
      "parent": "/dashboard_user"
    },
    "/dashboard_user/requests": {
      "filePath": "dashboard_user/requests.tsx",
      "parent": "/dashboard_user"
    },
    "/dashboard_user/tournament": {
      "filePath": "dashboard_user/tournament.tsx",
      "parent": "/dashboard_user"
    },
    "/dashboard_user/tuition": {
      "filePath": "dashboard_user/tuition.tsx",
      "parent": "/dashboard_user"
    },
    "/dashboard_admin/": {
      "filePath": "dashboard_admin/index.tsx",
      "parent": "/dashboard_admin"
    },
    "/dashboard_trainer/": {
      "filePath": "dashboard_trainer/index.tsx",
      "parent": "/dashboard_trainer"
    },
    "/dashboard_user/": {
      "filePath": "dashboard_user/index.tsx",
      "parent": "/dashboard_user"
    }
  }
}
ROUTE_MANIFEST_END */
